
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        // Thai fonts
        'sarabun': ['Sarabun', 'sans-serif'],
        'prompt': ['Prompt', 'sans-serif'],
        'kanit': ['Kanit', 'sans-serif'],
        'mitr': ['Mitr', 'sans-serif'],
        'trirong': ['Trirong', 'serif'],
        'athiti': ['Athiti', 'sans-serif'],
        'maitree': ['Maitree', 'serif'],
        'pridi': ['Pridi', 'serif'],
        'taviraj': ['Taviraj', 'serif'],
        'chakra-petch': ['Chakra Petch', 'sans-serif'],
        'chonburi': ['Chonburi', 'serif'],
        'fahkwang': ['Fahkwang', 'sans-serif'],
        'kodchasan': ['Kodchasan', 'sans-serif'],
        'k2d': ['K2D', 'sans-serif'],
        'niramit': ['Niramit', 'sans-serif'],
        'krub': ['Krub', 'sans-serif'],
        'bai-jamjuree': ['Bai Jamjuree', 'sans-serif'],
        'mali': ['Mali', 'sans-serif'],
        'srisakdi': ['Srisakdi', 'serif'],
        
        // Thai handwriting fonts
        'sriracha': ['Sriracha', 'cursive'],
        'charm': ['Charm', 'cursive'],
        'itim': ['Itim', 'cursive'],
        'pattaya': ['Pattaya', 'sans-serif'],
        'charmonman': ['Charmonman', 'cursive'],
        'mae-hongson': ['Sarabun', 'cursive'], // Fallback since Mae Hongson isn't in Google Fonts
        
        // English fonts
        'roboto': ['Roboto', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
        'montserrat': ['Montserrat', 'sans-serif'],
        'raleway': ['Raleway', 'sans-serif'],
        'lato': ['Lato', 'sans-serif'],
        'oswald': ['Oswald', 'sans-serif'],
        'merriweather': ['Merriweather', 'serif'],
        'playfair': ['Playfair Display', 'serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'source-sans': ['Source Sans Pro', 'sans-serif'],
        'nunito': ['Nunito', 'sans-serif'],
        'ubuntu': ['Ubuntu', 'sans-serif'],
        'lora': ['Lora', 'serif'],
        'quicksand': ['Quicksand', 'sans-serif'],
        'rubik': ['Rubik', 'sans-serif'],
        'work-sans': ['Work Sans', 'sans-serif'],
        'mulish': ['Mulish', 'sans-serif'],
        'titillium': ['Titillium Web', 'sans-serif'],
        'eb-garamond': ['EB Garamond', 'serif'],
        'bitter': ['Bitter', 'serif'],
        
        // English handwriting fonts
        'dancing-script': ['Dancing Script', 'cursive'],
        'caveat': ['Caveat', 'cursive'],
        'shadows-into-light': ['Shadows Into Light', 'cursive'],
        'indie-flower': ['Indie Flower', 'cursive'],
        'pacifico': ['Pacifico', 'cursive'],
        'kaushan-script': ['Kaushan Script', 'cursive'],
        'crafty-girls': ['Crafty Girls', 'cursive'],
        'sacramento': ['Sacramento', 'cursive'],
        'satisfy': ['Satisfy', 'cursive'],
        'amatic-sc': ['Amatic SC', 'cursive'],
        'permanent-marker': ['Permanent Marker', 'cursive'],
        'rock-salt': ['Rock Salt', 'cursive'],
        'reenie-beanie': ['Reenie Beanie', 'cursive'],
        'cedarville': ['Cedarville Cursive', 'cursive'],
        'damion': ['Damion', 'cursive'],
        
        // Additional fonts
        'architects-daughter': ['Architects Daughter', 'cursive'],
        'cormorant': ['Cormorant', 'serif'],
        'dm-sans': ['DM Sans', 'sans-serif'],
        'dm-serif': ['DM Serif Text', 'serif'],
        'exo': ['Exo', 'sans-serif'],
        'josefin-sans': ['Josefin Sans', 'sans-serif'],
        'manrope': ['Manrope', 'sans-serif'],
        'noto-sans': ['Noto Sans', 'sans-serif'],
        'noto-serif': ['Noto Serif', 'serif'],
        'patrick-hand': ['Patrick Hand', 'cursive'],
        'give-you-glory': ['Give You Glory', 'cursive'],
        'yellowtail': ['Yellowtail', 'cursive'],
        'covered': ['Covered By Your Grace', 'cursive'],
        'just-another-hand': ['Just Another Hand', 'cursive'],
        'pinyon-script': ['Pinyon Script', 'cursive'],
        'homemade-apple': ['Homemade Apple', 'cursive'],
        'allura': ['Allura', 'cursive'],
        'marck-script': ['Marck Script', 'cursive'],
        'kreon': ['Kreon', 'serif'],
        'oxygen': ['Oxygen', 'sans-serif'],
        'petit-formal-script': ['Petit Formal Script', 'cursive'],
      },
    },
  },
};
